# Generated by Django 5.2.16 on 2026-07-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(default='Konnect Projects', max_length=100)),
                ('admin_email', models.EmailField(default='admin@konnectprojects.com', max_length=254)),
                ('contact_number', models.CharField(default='9059598777', max_length=20)),
                ('whatsapp_number', models.CharField(default='9059598777', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='settings/')),
            ],
            options={
                'verbose_name_plural': 'Website Settings',
            },
        ),
    ]
