# Generated by Django 5.2.16 on 2026-07-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_websitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactenquiry',
            name='company_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='contactenquiry',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contactenquiry',
            name='preferred_contact_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactenquiry',
            name='preferred_contact_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactenquiry',
            name='property_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactenquiry',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactenquiry',
            name='service_interested_in',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactenquiry',
            name='source',
            field=models.CharField(blank=True, default='Website', max_length=100, null=True),
        ),
    ]
