# Generated by Django 5.2.16 on 2026-07-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactenquiry_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuserprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
