# Generated by Django 5.2.16 on 2026-08-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_adminuserprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactenquiry',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactenquiry',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Follow Up', 'Follow Up'), ('Interested', 'Interested'), ('Site Visit', 'Site Visit'), ('Negotiation', 'Negotiation'), ('Sold', 'Sold'), ('Not Interested', 'Not Interested'), ('Closed', 'Closed')], default='New', max_length=20),
        ),
    ]
